#!/usr/bin/python
"""
Author: Vertigo Designs, Ryan Summers
        Robert Jördens

Description: Provides an API for controlling Miniconf devices over MQTT.
"""
import asyncio
import json
import logging
import uuid
import warnings

from gmqtt import Client as MqttClient

LOGGER = logging.getLogger(__name__)

class MiniconfException(Exception):
    """ Generic exceptions generated by Miniconf. """


class Miniconf:
    """An asynchronous API for controlling Miniconf devices using MQTT."""

    @classmethod
    async def create(cls, prefix, broker):
        """Create a connection to the broker and a Miniconf device using it."""
        client = MqttClient(client_id='')
        await client.connect(broker)
        return cls(client, prefix)

    def __init__(self, client, prefix):
        """Constructor.

        Args:
            client: A connected MQTT5 client.
            prefix: The MQTT toptic prefix of the device to control.
        """
        self.client = client
        self.prefix = prefix
        self.inflight = {}
        self.client.on_message = self._handle_response
        self.client.on_subscribe = self._handle_subscription
        self.response_topic = f'{prefix}/response'
        self.client.subscribe(f'{prefix}/response')
        self._pending_subscriptions = {}


    def _handle_subscription(self, client, mid, qos, props):
        LOGGER.info("Handling subscription for %s", mid)
        if mid not in self._pending_subscriptions:
            return

        self._pending_subscriptions[mid].set_result(True)
        del self._pending_subscriptions[mid]


    def _handle_response(self, _client, topic, payload, _qos, properties):
        """Callback function for when messages are received over MQTT.

        Args:
            _client: The MQTT client.
            topic: The topic that the message was received on.
            payload: The payload of the message.
            _qos: The quality-of-service level of the received packet
            properties: A dictionary of properties associated with the message.
        """
        if 'correlation_data' not in properties:
            LOGGER.warn("Discarding message without CD")
            return

        # Extract request_id corrleation data from the properties
        request_id = properties['correlation_data'][0]

        if request_id not in self.inflight:
            LOGGER.info("Discarding message with CD: %s", request_id)
            return

        response = json.loads(payload)
        if topic == self.response_topic:
            # Handle list responses
            if isinstance(self.inflight[request_id], tuple):
                if response['code'] == 0xFF:
                    self.inflight[request_id][1].set_result(response)
                    del self.inflight[request_id]
                elif response['code'] == 0:
                    self.inflight[request_id][1].set_result(self.inflight[request_id][0])
                    del self.inflight[request_id]
                else:
                    self.inflight[request_id][0].append(response["msg"])

            # Handle get/set responses
            else:
                self.inflight[request_id].set_result((response, self.inflight[request_id][0]))
                del self.inflight[request_id]
        else:
            # Handle get subscription data.
            self.inflight[request_id][0] = response



    async def command(self, *args, **kwargs):
        """ Refer to `set` for more information. """
        warnings.warn("The `command` API function is deprecated in favor of `set`",
                      DeprecationWarning)
        return self.set(*args, **kwargs)


    async def set(self, path, value, retain=False, timeout=5):
        """Write the provided data to the specified path.

        Args:
            path: The path to write the message to.
            value: The value to write to the path.
            retain: Retain the MQTT message changing the setting
                by the broker.
            timeout: The maximum time to wait for the response in seconds.

        Returns:
            The response to the command as a dictionary.
        """
        topic = f'{self.prefix}/settings/{path}'

        fut = asyncio.get_running_loop().create_future()

        # Assign unique correlation data for response dispatch
        request_id = uuid.uuid1().hex.encode()
        assert request_id not in self.inflight
        self.inflight[request_id] = fut

        payload = json.dumps(value, separators=(",", ":"))
        LOGGER.info('Sending "%s" to "%s" with CD: %s', value, topic, request_id)

        self.client.publish(
            topic, payload=payload, qos=0, retain=retain,
            response_topic=self.response_topic,
            correlation_data=request_id)

        result = await asyncio.wait_for(fut, timeout)
        if result['code'] != 0:
            raise MiniconfException(result['msg'])


    def list_paths(self):
        """ Get a list of all the paths available on the device. """
        self._topics = []
        fut = asyncio.get_running_loop().create_future()

        request_id = uuid.uuid1().hex.encode()
        assert request_id not in self.inflight
        self.inflight[request_id] = ([], fut)

        self.client.publish(f'{self.prefix}/list', payload='',
                            correlation_data=request_id,
                            response_topic=self.response_topic)
        return fut


    async def get(self, path, timeout=5):
        """ Get the specific value of a given path. """
        fut = asyncio.get_running_loop().create_future()

        # Assign unique correlation data for response dispatch
        request_id = uuid.uuid1().hex.encode()
        assert request_id not in self.inflight
        self.inflight[request_id] = [None, fut]

        subscription = self.client.subscribe(f'{self.prefix}/settings/{path}', no_local=True)
        self._pending_subscriptions[subscription] = asyncio.get_running_loop().create_future()
        await self._pending_subscriptions[subscription]

        self.client.publish(
            f'{self.prefix}/settings/{path}', payload='', qos=0,
            response_topic=self.response_topic,
            correlation_data=request_id)

        result, value = await asyncio.wait_for(fut, timeout)

        self.client.unsubscribe(f'{self.prefix}/settings/{path}')

        if result['code'] != 0:
            raise MiniconfException(result['msg'])

        return value
