[package]
name = "miniconf-benchmark"
version = "0.0.0"
edition = "2024"
publish = false

[dependencies]
cortex-m-rt = { version = "0.7", features = ["paint-stack"] }
cortex-m-semihosting = "0.5"
panic-halt = "1.0"
miniconf = { path = "../../../miniconf", default-features = false, features = ["derive"] }
serde = { version = "1.0", default-features = false, features = ["derive"] }
serde-json-core = { version = "0.6", default-features = false }
heapless = { version = "0.8", optional = true }

[workspace]

[features]
tree = ["miniconf/json-core"]
help = ["miniconf/meta-node", "miniconf/meta-edge", "miniconf/sem", "dep:heapless"]

[profile.release]
codegen-units = 1
incremental = false
lto = true
opt-level = "s"
debug = true
